name: Flush Cache

on:
  release:
    types: [published]

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-22.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/potatoshield@1/dist/potatoshield.js